### ISSUE TITLE
System.TypeInitializationException using MemberwiseEquatable<T> with empty class

### ISSUE THREAD

**Issue by gyulakrizsma** [thedmi/Equ#3]
Given the following class:

```
public class ValueObj : MemberwiseEquatable<ValueObj> { }
```

Produces a System.TypeInitializationException: 
> The type initializer for 'Equ.MemberwiseEquatable`1' threw an exception.

```
System.InvalidOperationException
Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at Equ.EqualityFunctionGenerator.MakeEqualsMethod()
   at Equ.MemberwiseEqualityComparer`1..ctor(EqualityFunctionGenerator equalityFunctionGenerator)
   at Equ.MemberwiseEqualityComparer`1.<.cctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Equ.MemberwiseEquatable`1..cctor()
```

The same problem exists for cases where the class contains only computed properties.

**Comment by thedmi** [comment]
Fixed in 1.0.4
